# Generated by Django 5.0.2 on 2024-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
