# Generated by Django 5.0.2 on 2024-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_order_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Precio',
            field=models.IntegerField(default=False),
        ),
    ]
