# Generated by Django 5.0.2 on 2024-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_rename_user_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Completado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Precio',
            field=models.IntegerField(),
        ),
    ]
